
from libc.float cimport FLT_MIN as _FLT_MIN, FLT_MAX as _FLT_MAX, DBL_MIN as _DBL_MIN, DBL_MAX as _DBL_MAX

from libc.limits cimport CHAR_MIN as _CHAR_MIN, CHAR_MAX as _CHAR_MAX, SCHAR_MIN as _SCHAR_MIN, \
    SCHAR_MAX as _SCHAR_MAX, UCHAR_MAX as _UCHAR_MAX, SHRT_MIN as _SHRT_MIN, SHRT_MAX as _SHRT_MAX, \
    USHRT_MAX as _USHRT_MAX, INT_MIN as _INT_MIN, INT_MAX as _INT_MAX, UINT_MAX as _UINT_MAX, LONG_MIN as _LONG_MIN, \
    LONG_MAX as _LONG_MAX, ULONG_MAX as _ULONG_MAX, LLONG_MIN as _LLONG_MIN, LLONG_MAX as _LLONG_MAX, \
    ULLONG_MAX as _ULLONG_MAX

CHAR_MIN = _CHAR_MIN
CHAR_MAX = _CHAR_MAX
SCHAR_MIN = _SCHAR_MIN
SCHAR_MAX = _SCHAR_MAX
UCHAR_MAX = _UCHAR_MAX
SHRT_MIN = _SHRT_MIN
SHRT_MAX = _SHRT_MAX
USHRT_MAX = _USHRT_MAX
INT_MIN = _INT_MIN
INT_MAX = _INT_MAX
UINT_MAX = _UINT_MAX
LONG_MIN = _LONG_MIN
LONG_MAX = _LONG_MAX
ULONG_MAX = _ULONG_MAX
LLONG_MIN = _LLONG_MIN
LLONG_MAX = _LLONG_MAX
ULLONG_MAX = _ULLONG_MAX
FLT_MIN = _FLT_MIN
FLT_MAX = _FLT_MAX
DBL_MIN = _DBL_MIN
DBL_MAX = _DBL_MAX