# yamllint disable rule:line-length

name: 'Publish - test.pypi.org'

# yamllint disable rule:truthy
on:
  workflow_run:
    workflows: ['Lint', 'Test']
    tags: ['*']
    types:
      - completed
# yamllint enable rule:truthy

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build sdist
        shell: bash
        run: |
          set -ueo pipefail

          pip3 install -v --upgrade \
            "pip >= 22.2.2" \
            "setuptools >= 65.4.1" \
            "cython >= 0.29.0"

          python setup.py sdist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
          print_hash: true
