# yamllint disable rule:line-length

name: Test

# yamllint disable rule:truthy
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
# yamllint enable rule:truthy

env:
  DEPS_UBUNTU: libboost-all-dev
  DEPS_MACOS: boost
  DEPS_WINDOWS: boost-msvc-14.3

jobs:
  lint:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   python-version: '3.7'
          # - os: ubuntu-latest
          #   python-version: '3.8'
          # - os: ubuntu-latest
          #   python-version: '3.9'
          # - os: ubuntu-latest
          #   python-version: '3.10'
          # - os: ubuntu-latest
          #   python-version: 'pypy3.9'
          # - os: macos-latest
          #   python-version: '3.10'
          - os: windows-latest
            python-version: '3.10'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages (Linux)
        shell: bash
        if: ${{ runner.os == 'Linux' && env.DEPS_UBUNTU }}
        run: |
          set -ueo pipefail
          sudo add-apt-repository ppa:apt-fast/stable
          sudo apt-get update
          sudo apt-get -y install apt-fast
          sudo apt-fast -y install $DEPS_UBUNTU

      - name: Install packages (macOs)
        shell: bash
        if: ${{ runner.os == 'macOS' && env.DEPS_MACOS }}
        run: |
          set -ueo pipefail
          brew install $DEPS_MACOS

      - name: Install packages (Windows)
        shell: powershell
        if: ${{ runner.os == 'Windows' && env.DEPS_WINDOWS }}
        run: |
          choco install --no-progress -y ${{ env.DEPS_WINDOWS }}
          Get-ChildItem c:\local -Name
          Get-ChildItem c:\local\boost_1_80_0 -Name

      - name: Test (Unix)
        shell: bash
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: |
          set -ueo pipefail
          egg=${GITHUB_REPOSITORY/[a-zA-Z0-9\-_\.]*\//}
          pip install -e file:///$(pwd)#egg=${egg}[dev]
          pytest

      - name: Test (Windows)
        shell: powershell
        if: ${{ runner.os == 'Windows' }}
        run: |
          pip install -e .[dev]
          pytest
