# yamllint disable rule:line-length

name: Test

# yamllint disable rule:truthy
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
# yamllint enable rule:truthy

env:
  DEPS_UBUNTU: libboost-all-dev
  DEPS_MACOS: boost
  DEPS_WINDOWS: boost-msvc-14.3

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.7'
          - os: ubuntu-latest
            python-version: '3.8'
          - os: ubuntu-latest
            python-version: '3.9'
          - os: ubuntu-latest
            python-version: '3.10'
            # Test using BOOST_ROOT on ubuntu
            boost-root: '/usr'
          - os: ubuntu-latest
            python-version: '3.10'
          - os: ubuntu-latest
            python-version: 'pypy3.9'
          - os: macos-latest
            python-version: '3.10'
          # - os: macos-latest
          #   python-version: '3.10'
          #   boost-root: ''  # Test using BOOST_ROOT on macOS
          - os: windows-latest
            python-version: '3.10'
            boost-root: 'C:\local\boost_1_80_0'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages (Linux)
        shell: bash
        if: ${{ runner.os == 'Linux' && env.DEPS_UBUNTU }}
        run: |
          set -ueo pipefail

          sudo apt-get update
          sudo apt-get -y install $DEPS_UBUNTU

          # # Faster but unnecessary for small amount of deps
          # sudo add-apt-repository ppa:apt-fast/stable
          # sudo apt-get update
          # sudo apt-get -y install apt-fast
          # sudo apt-fast -y install $DEPS_UBUNTU

          pip3 install -v --upgrade \
            "pip >= 22.2.2" \
            "setuptools >= 65.4.1" \
            "cython >= 0.29.0"

      - name: Install packages (macOs)
        shell: bash
        if: ${{ runner.os == 'macOS' && env.DEPS_MACOS }}
        run: |
          set -ueo pipefail
          brew install $DEPS_MACOS
          brew info $DEPS_MACOS
          pip3 install -v --upgrade \
            "pip >= 22.2.2" \
            "setuptools >= 65.4.1" \
            "cython >= 0.29.0"

      - name: Install packages (Windows)
        shell: powershell
        if: ${{ runner.os == 'Windows' && env.DEPS_WINDOWS }}
        run: |
          choco install --no-progress -y ${{ env.DEPS_WINDOWS }}

          ## List items in C:\local
          # (Get-ChildItem -Path 'C:\local\' -Force -Recurse -ErrorAction 'SilentlyContinue').FullName

          pip3 install --upgrade "pip >= 22.2.2" "setuptools >= 65.4.1" "cython >= 0.29.0"

      - name: Test (Unix)
        shell: bash
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: |
          set -ueo pipefail
          export BOOST_ROOT='${{ matrix.boost-root }}'
          pip install .[dev]
          pytest

      - name: Test (Windows)
        shell: powershell
        if: ${{ runner.os == 'Windows' }}
        run: |
          $env:BOOST_ROOT = '${{ matrix.boost-root }}'

          pip install .[dev]
          pytest

  publish-test:
    name: Publish to test.pypy.org
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.ref, '/tags/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build sdist
        shell: bash
        run: |
          set -ueo pipefail

          pip3 install -v --upgrade \
            "pip >= 22.2.2" \
            "setuptools >= 65.4.1" \
            "cython >= 0.29.0"

          python setup.py sdist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          verbose: true
          print_hash: true
